name: Cloudguard-ShiftLeft-Scans
on:
  push:
    branches: [ master ]
    paths: 
      - '*'
      - '!README.md'
      - '!.github/workflows/**'
      
  pull_request:
    branches: [ master ]
    paths: 
      - '*'
      - '!README.md'
      - '!.github/workflows/**'
      
  workflow_dispatch:
  
jobs:
  Image_Scanner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the webapp container and save image
        run: |
          docker build . --tag pawanjitghatora/dotnet-example-api:main
          docker save pawanjitghatora/dotnet-example-api:main -o webapp.tar
      - name: Run Shiftleft assessment on saved image
        run: |  
          docker pull checkpoint/shiftleft
          docker run -v=$(pwd):/tmp/ -e "CHKP_CLOUDGUARD_ID=${{ secrets.CHKP_CLOUDGUARD_ID }}" -e "CHKP_CLOUDGUARD_SECRET=${{ secrets.CHKP_CLOUDGUARD_SECRET }}" -e "SHIFTLEFT_REGION=${{ secrets.SHIFTLEFT_REGION }}" checkpoint/shiftleft shiftleft image-scan -r -2000 -e e5ac2e74-e7b9-4741-8851-29a14bf9122f -i /tmp/webapp.tar || exit 0
